import {hubIdentity} from './portal-auth';
import {integratedWorkflows,prepareWorkflowNote,type WorkflowPreview,type WorkflowSource} from '../lib/workflows/integrated';
const root=document.querySelector<HTMLElement>('[data-integrated-workflows]');
if(root){
 const owner=()=>hubIdentity.status==='signed-in'?hubIdentity.id:null;
 const status=root.querySelector<HTMLElement>('[data-workflow-status]')!,panel=root.querySelector<HTMLElement>('[data-workflow-preview]')!,heading=root.querySelector<HTMLElement>('[data-workflow-title]')!,destination=root.querySelector<HTMLElement>('[data-workflow-destination]')!,explanation=root.querySelector<HTMLElement>('[data-workflow-explanation]')!,text=root.querySelector<HTMLElement>('[data-workflow-note]')!;
 const confirm=root.querySelector<HTMLButtonElement>('[data-workflow-confirm]')!,handoff=root.querySelector<HTMLAnchorElement>('[data-workflow-handoff]')!;
 let preview:WorkflowPreview|null=null,captureOwner:string|null=null,timer:ReturnType<typeof setTimeout>|undefined;
 function clearPreview(){if(preview)integratedWorkflows.cancel(preview.id);preview=null;captureOwner=null;clearTimeout(timer);panel.hidden=true;heading.textContent=destination.textContent=explanation.textContent=text.textContent='';handoff.hidden=true;handoff.removeAttribute('href');confirm.hidden=false;}
 function show(p:WorkflowPreview){clearPreview();preview=p;panel.hidden=false;heading.textContent=p.title;destination.textContent='Destination: '+p.destination+' · '+(hubIdentity.status==='signed-in'?hubIdentity.label:'');text.textContent=p.note?.content??'';explanation.textContent=p.kind==='reading-note'?'Confirm copies this browser’s book metadata into a recoverable draft for your selected Notes account. Review/edit the draft and separately confirm Save. Existing drafts are preserved.':'This is a cloud due-review snapshot. TMS60 opens the exact translation, verse and recall dimension using its local progress. Check its account and current progress before practising.';timer=setTimeout(()=>{clearPreview();render();status.textContent='Source snapshot expired. Refresh the owning app before confirming.';},Math.max(0,p.expiresAt-Date.now()));}
 function render(){clearPreview();for(const source of ['library','tms60'] as WorkflowSource[]){const list=root!.querySelector<HTMLElement>('[data-workflow-'+source+']')!;list.replaceChildren();const items=integratedWorkflows.choices(source,owner());for(const item of items){const li=document.createElement('li'),button=document.createElement('button');button.type='button';button.className='portal-button';button.textContent='Preview: '+item.title+(source==='tms60'?' · '+item.dimension:'');button.addEventListener('click',()=>{const id=owner();if(!id||root!.hidden||document.hidden)return;try{show(integratedWorkflows.preview(source,item.resourceId,id));status.textContent='Review this destination before confirming.';}catch{status.textContent='Source is unavailable. Refresh it and choose again.';}});li.append(button);list.append(li);}if(!items.length){const li=document.createElement('li');li.textContent='No fresh choices are available. Connect or refresh this source.';list.append(li);}}root!.querySelector<HTMLButtonElement>('[data-workflow-capture]')!.disabled=!owner()||Boolean(root!.hidden)||document.hidden;}
 root.querySelector('[data-workflow-capture]')!.addEventListener('click',()=>{clearPreview();captureOwner=owner();if(!captureOwner)return;panel.hidden=false;heading.textContent='Capture a thought';destination.textContent='Destination: Notes · Unfiled · selected Hub account · '+(hubIdentity.status==='signed-in'?hubIdentity.label:'');explanation.textContent='Confirm opens your account’s recoverable capture draft. You choose the text and separately confirm Save to Notes.';status.textContent='Review your signed-in account and destination.';});
 confirm.addEventListener('click',()=>{const id=owner();if(!id||root!.hidden||document.hidden)return;try{if(captureOwner){if(captureOwner!==id)throw Error();prepareWorkflowNote(id);clearPreview();status.textContent='Capture draft ready below. Connect capture, review your text, then Save to Notes.';return;}if(!preview)throw Error();const p=integratedWorkflows.confirm(preview.id,id);if(p.kind==='reading-note'){prepareWorkflowNote(id,p.note);clearPreview();panel.hidden=false;heading.textContent=p.title;destination.textContent='Study-note draft prepared in Notes capture';handoff.href=p.href;handoff.textContent='Resume reading (new tab)';handoff.hidden=false;confirm.hidden=true;timer=setTimeout(clearPreview,Math.max(0,p.expiresAt-Date.now()));status.textContent='Study-note draft prepared below. Its metadata is saved in this browser; edit, connect capture and Save to Notes.';}else{integratedWorkflows.cancel(p.id);confirm.hidden=true;handoff.href=p.href;handoff.textContent='Open confirmed TMS60 destination (new tab)';handoff.hidden=false;status.textContent='Destination confirmed. Open TMS60, then check its account and local review state. No review has been completed.';}}catch{status.textContent='Destination unavailable or preview expired. Existing drafts remain intact. Recover or reconcile your capture draft before preparing another.';}});
 root.querySelector('[data-workflow-cancel]')!.addEventListener('click',()=>{clearPreview();status.textContent='Preview cancelled. No destination write occurred.';});
 integratedWorkflows.subscribe(render);
 function clear(){integratedWorkflows.clear();clearPreview();status.textContent='Sources have been cleared. Connect them again to choose fresh work.';render();}
 window.addEventListener('hub:identity',clear);window.addEventListener('pagehide',clear);window.addEventListener('pageshow',e=>{if(e.persisted)clear();});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();else render();});
 new MutationObserver(()=>{if(root!.hidden)clear();else render();}).observe(root,{attributes:true,attributeFilter:['hidden']});render();
}
