from pathlib import Path
p=Path('tests/studio/studio.spec.ts')
s=p.read_text()
s=s.replace("import routes from '../../src/generated/route-manifest.json';", "const routes: {routes:string[]} = JSON.parse(fs.readFileSync('src/generated/route-manifest.json','utf8'));")
s=s.replace("import config from '../../src/data/showcase.json';", "const config: {hero:string;work:string[];projects:Record<string,{media:string}>} = JSON.parse(fs.readFileSync('src/data/showcase.json','utf8'));")
p.write_text(s)
p=Path('src/pages/index.astro');s=p.read_text().replace('Some ideas need<br/>more than a screen.','Some ideas take<br/>a little longer.');p.write_text(s)
p=Path('src/content/projects/micro-arcade.md');s=p.read_text().replace('31 instant-play browser games','Instant-play browser games').replace('A 31-game browser arcade','A browser arcade').replace('31-game arcade','A varied arcade library').replace('The real 31-game library','The real game library').replace('packages thirty-one small games','packages a growing collection of small games');p.write_text(s)
p=Path('src/content/projects/pdf-studio.md');s=p.read_text().replace('The record therefore treats privacy and document consequence as part of the interaction, not as a footer claim.','Document operations stay together in one workspace, with local processing as a central design constraint.');p.write_text(s)
p=Path('scripts/capture-studio.mjs');s=p.read_text();s=s.replace("await page.getByRole('button',{name:action,exact:true}).first().click();", "if(app==='tbc'){const beginner=page.getByRole('button',{name:/1\\s+Beginner/}).first();if(await beginner.isVisible())await beginner.click();await page.getByRole('button',{name:/^Quick Play/}).filter({visible:true}).first().click();}else await page.getByRole('button',{name:action,exact:true}).first().click();")
p.write_text(s)
print('Applied test-loader and editorial corrections.')
