import { describe, expect, it, vi } from 'vitest';
import { HubNotesSession, INBOX_PENDING_KEY, NOTES_ISSUER, parseNotesConsent } from '../../src/lib/hub-notes-session';
const A='11111111-1111-4111-8111-111111111111', C='33333333-3333-4333-8333-333333333333', REV='44444444-4444-4444-8444-444444444444';
const now=Date.parse('2026-10-05T12:00:00Z'),consent={permissions:['notes.hub.inbox.read','notes.hub.inbox.attention.write'],revision:REV};
function fixture(){
 const data=new Map<string,string>(),storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v);},removeItem:(k:string)=>{data.delete(k);}};
 const bearer='eyJhbGciOiJFUzI1NiJ9.'+Buffer.from(JSON.stringify({sub:A,client_id:C,session_id:REV,iss:NOTES_ISSUER+'/auth/v1',aud:'authenticated',role:'authenticated',exp:Math.floor(now/1000)+3600})).toString('base64url')+'.fictional_signature';
 const http=vi.fn(async(url:RequestInfo|URL,init?:RequestInit)=>{
  if(String(url).endsWith('/oauth/token')){expect(new URLSearchParams(String(init?.body)).get('redirect_uri')).toBe('https://thiepn.dev/inbox/');return Response.json({access_token:bearer,refresh_token:'inbox_refresh_sentinel',token_type:'bearer',expires_in:3600});}
  expect(String(url)).toBe(NOTES_ISSUER+'/rest/v1/rpc/thiepn_hub_notes_inbox');const r=JSON.parse(String(init?.body));
  return Response.json({schemaVersion:1,providerId:'notes',operation:'inbox',requestId:r.p_request_id,context:{scope:'account',accountId:A,workspaceId:null,grantRevision:REV,translationId:null},status:'ready',privacy:'private',coverage:'cloud-snapshot',observedAt:new Date(now).toISOString(),expiresAt:new Date(now+120000).toISOString(),sourceUpdatedAt:null,data:{items:[{issueId:'reminder:'+A,dedupeKey:'reminder:'+A,title:'Fictional reminder',type:'reminder',severity:'normal',state:'open',attention:r.p_action==='dismiss'?'dismissed':'unread',updatedAt:new Date(now-1000).toISOString(),expiresAt:null,actionKey:'open'}]}});
 });
 const session=new HubNotesSession({inbox:true,clientId:C,platformOrigin:'',publishableKey:'sb_publishable_fictional'},storage,()=>A,http,()=>now);return{session,storage,data,http};
}
async function connect(f:ReturnType<typeof fixture>){const url=new URL(await f.session.begin(A,consent));expect(url.searchParams.get('redirect_uri')).toBe('https://thiepn.dev/inbox/');const p=JSON.parse(f.storage.getItem(INBOX_PENDING_KEY)!);await f.session.complete(new URLSearchParams({code:'fictional-code',state:p.state}),'');}
describe('H17 managed Inbox session',()=>{
 it('binds the Inbox callback, exact context and purpose; tokens stay in RAM',async()=>{const f=fixture();await connect(f);expect(f.data.size).toBe(0);const access=await f.session.inboxAccess(consent);const request={providerId:'notes' as const,operation:'inbox' as const,requestId:crypto.randomUUID(),context:access.context};expect(JSON.parse(await f.session.readAttention(request,new AbortController().signal)).data.items[0].type).toBe('reminder');expect(f.data.size).toBe(0);});
 it('sends action preconditions in a POST body, never the URL',async()=>{const f=fixture();await connect(f);const access=await f.session.inboxAccess(consent),request={providerId:'notes' as const,operation:'inbox' as const,requestId:crypto.randomUUID(),context:access.context,issueId:'reminder:'+A,action:'dismiss' as const,expectedUpdatedAt:new Date(now-1000).toISOString()};await f.session.readAttention(request,new AbortController().signal);expect(JSON.parse(String(f.http.mock.calls[1]![1]?.body))).toMatchObject({p_action:'dismiss',p_issue_id:'reminder:'+A,p_expected_updated_at:request.expectedUpdatedAt});expect(f.http.mock.calls.every(([url])=>!String(url).includes('reminder:'))).toBe(true);});
 it('rejects a changed revision or wrong owner before private reads',async()=>{const f=fixture();await connect(f);await expect(f.session.inboxAccess({...consent,revision:A})).rejects.toThrow();const access=await f.session.inboxAccess(consent);await expect(f.session.readAttention({providerId:'notes',operation:'inbox',requestId:crypto.randomUUID(),context:{...access.context,accountId:C} as any},new AbortController().signal)).rejects.toThrow();expect(f.http).toHaveBeenCalledTimes(1);});
 it('rejects Home-only and write-only consent, including TMS purpose substitution',async()=>{const f=fixture();await expect(f.session.begin(A,{permissions:['notes.hub.summary.read'],revision:REV})).rejects.toThrow();expect(()=>parseNotesConsent({permissions:['notes.hub.inbox.attention.write'],revision:REV})).toThrow();expect(()=>parseNotesConsent({permissions:['tms60.hub.inbox.read'],revision:REV},'tms60')).toThrow();expect(f.http).not.toHaveBeenCalled();});
});
