import {describe,it,expect} from 'vitest';
import {IntegratedWorkflows} from '../../src/lib/workflows/integrated';
import type {ProviderEnvelope} from '../../src/lib/providers/types';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222';
const now=Date.now();
function envelope(provider:'library'|'tms60',operation:'summary'|'continue'='summary'):ProviderEnvelope{return {schemaVersion:1,providerId:provider,operation,requestId:A,context:provider==='library'?{scope:'device',deviceId:A,consentRevision:B}:{scope:'account',accountId:A,workspaceId:null,grantRevision:B,translationId:'esv'},status:'ready',privacy:'private',coverage:provider==='library'?'device-local':'translation-cloud-snapshot',observedAt:new Date(now-1000).toISOString(),expiresAt:new Date(now+10000).toISOString(),sourceUpdatedAt:null,data:{items:[provider==='library'?{resourceId:'book-1',title:'<b>Book</b>',updatedAt:new Date(now-1000).toISOString(),format:'epub',edition:2,releaseVersion:'release-1',current:.2,furthest:.8}:{resourceId:'esv:1:wording',title:'John 3:16',updatedAt:new Date(now-1000).toISOString(),dimension:'wording'}],...(provider==='tms60'&&operation==='summary'?{dueTaskCount:1,dueVerseCount:1,newVerseCount:0}:{})}};}
describe('explicit cross-app workflows',()=>{
 it('previews device provenance and exact revision-qualified resume URL',()=>{const w=new IntegratedWorkflows(()=>now);w.publish(envelope('library'));const p=w.preview('library','book-1',A);expect(p.note?.content).toContain('not account-synced');expect(p.note?.content).toContain('Current progress: 20% · furthest: 80%');expect(p.href).toBe('https://thiepn.dev/library/hub/continue?resource=book-1&edition=2&release=release-1');expect(w.confirm(p.id,A)).toEqual(p);});
 it('opens exact TMS translation and dimension without a progress write',()=>{const w=new IntegratedWorkflows(()=>now);w.publish(envelope('tms60'));const p=w.preview('tms60','esv:1:wording',A);expect(p.href).toBe('https://tms60.thiepn.dev/#hub=esv%3A1%3Awording');expect(p.note).toBeUndefined();});
 it('never presents another account’s cloud references',()=>{const w=new IntegratedWorkflows(()=>now);w.publish(envelope('tms60'));expect(w.choices('tms60',B)).toEqual([]);expect(()=>w.preview('tms60','esv:1:wording',B)).toThrow();});
 it('rejects confirmation after changing the destination account',()=>{const w=new IntegratedWorkflows(()=>now);w.publish(envelope('library'));const p=w.preview('library','book-1',A);expect(()=>w.confirm(p.id,B)).toThrow();});
 it('rejects expiry without interaction and refuses stale preview creation',()=>{let time=now;const w=new IntegratedWorkflows(()=>time);w.publish(envelope('library'));const p=w.preview('library','book-1',A);time+=10001;expect(()=>w.confirm(p.id,A)).toThrow();expect(w.choices('library',A)).toEqual([]);});
 it('invalidates old previews on source refresh or revocation',()=>{const w=new IntegratedWorkflows(()=>now);w.publish(envelope('library'));const p=w.preview('library','book-1',A);w.publish(envelope('library'));expect(()=>w.confirm(p.id,A)).toThrow();const q=w.preview('library','book-1',A);w.clear('library');expect(()=>w.confirm(q.id,A)).toThrow();});
 it('does not misclassify recent practice as due review',()=>{const w=new IntegratedWorkflows(()=>now);w.publish(envelope('tms60','continue'));expect(w.choices('tms60',A)).toEqual([]);});
 it('rejects malformed owner records instead of inventing a workflow',()=>{const w=new IntegratedWorkflows(()=>now),e=envelope('library');e.data!.items[0]!.releaseVersion='unsafe/url';expect(()=>w.publish(e)).toThrow();});
 it('retains a confirmed selection until destination preparation succeeds',()=>{const w=new IntegratedWorkflows(()=>now);w.publish(envelope('library'));const p=w.preview('library','book-1',A);expect(w.confirm(p.id,A)).toEqual(w.confirm(p.id,A));w.cancel(p.id);expect(()=>w.confirm(p.id,A)).toThrow();});
});
