import {describe,it,expect,vi} from 'vitest';
import {NotesCapture,captureDraftKey,type CaptureCommand,type CaptureReceipt} from '../../src/lib/notes-capture';
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
function setup(){let id:string|null=owner;const data=new Map<string,string>();const storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v);},removeItem:(k:string)=>{data.delete(k);}};const receipt=(c:CaptureCommand):CaptureReceipt=>({schemaVersion:1,accountId:c.accountId,grantRevision:owner,requestId:c.requestId,destination:c.destination,noteId:other,createdAt:1,status:'confirmed'});const send=vi.fn(async(c:CaptureCommand)=>receipt(c));return {data,storage,send,receipt,setOwner:(v:string|null)=>{id=v;},build:()=>new NotesCapture(owner,storage,()=>id,send)};}
describe('recoverable owner-bound capture',()=>{
 it('persists edited drafts through reload',()=>{const f=setup(),d=f.build();d.edit('title','content');expect(f.build().snapshot()).toMatchObject({title:'title',content:'content',state:'draft'});});
 it('stores uncertainty before network and retries identical commands after lost confirmation',async()=>{const f=setup(),d=f.build();d.edit('a','b');f.send.mockImplementationOnce(async()=>{expect(f.build().snapshot().state).toBe('uncertain');throw Error('timeout');});await expect(d.save(new AbortController().signal)).rejects.toThrow();const recovered=f.build();await recovered.save(new AbortController().signal);expect(f.send.mock.calls[1]![0]).toEqual(f.send.mock.calls[0]![0]);expect(recovered.snapshot().state).toBe('confirmed');});
 it('blocks parallel submissions and edits of an uncertain command',async()=>{const f=setup(),d=f.build();d.edit('a','b');let resolve!:(r:CaptureReceipt)=>void;f.send.mockImplementation(c=>new Promise(r=>{resolve=r;}));const pending=d.save(new AbortController().signal);await expect(d.save(new AbortController().signal)).rejects.toThrow();expect(()=>d.edit('changed','')).toThrow();resolve(f.receipt(f.send.mock.calls[0]![0]));await pending;expect(f.send).toHaveBeenCalledTimes(1);});
 it('never redirects an old draft after account changes',async()=>{const f=setup(),d=f.build();d.edit('secret','body');f.setOwner(other);await expect(d.save(new AbortController().signal)).rejects.toThrow();expect(f.send).not.toHaveBeenCalled();expect(f.data.has(captureDraftKey(owner))).toBe(true);});
 it('ignores a confirmation that arrives after clearing or switching',async()=>{const f=setup(),d=f.build();d.edit('a','b');f.send.mockImplementation(async c=>{d.clear();return f.receipt(c);});await expect(d.save(new AbortController().signal)).rejects.toThrow();expect(f.build().snapshot().state).toBe('uncertain');});
 it('rejects wrong-owner receipts and retains command',async()=>{const f=setup(),d=f.build();d.edit('a','b');f.send.mockImplementation(async c=>({...f.receipt(c),accountId:other}));await expect(d.save(new AbortController().signal)).rejects.toThrow();expect(d.snapshot().state).toBe('uncertain');});
 it('does not send if durable storage fails',async()=>{const f=setup(),d=f.build();d.edit('a','b');f.storage.setItem=()=>{throw Error('quota');};await expect(d.save(new AbortController().signal)).rejects.toThrow('quota');expect(f.send).not.toHaveBeenCalled();});
 it('requires reconciliation before replacing or erasing an uncertain draft',async()=>{const f=setup(),d=f.build();d.edit('a','b');f.send.mockRejectedValueOnce(Error());await expect(d.save(new AbortController().signal)).rejects.toThrow();expect(()=>d.newDraft()).toThrow();expect(()=>d.erase()).toThrow();});
 it('creates a new request only after confirmation',async()=>{const f=setup(),d=f.build();d.edit('a','b');const first=d.snapshot().requestId;await d.save(new AbortController().signal);d.newDraft();expect(d.snapshot()).toMatchObject({state:'draft',title:'',content:''});expect(d.snapshot().requestId).not.toBe(first);});
});
