import{afterEach,describe,expect,it,vi}from'vitest';
import{validateEnvironmentContract,validateFiles,validateProduct,validateRepoPolicy}from'../../scripts/vercel/validate-product-family.mjs';
import{auditEnvironmentMetadata,fetchEnvironmentMetadata}from'../../scripts/vercel/audit-environment-contract.mjs';
import{validateConfirmation,validateDeploymentUrl,validateSourceSha}from'../../scripts/vercel/release-control.mjs';
const product={schemaVersion:1,productId:'hub',family:'hub',projectName:'thiepn-hub',repository:'thiepn/thiepn.github.io',framework:'astro',nodeMajor:24,vercelCliVersion:'50.1.0',deployment:{mode:'manual-cli',gitIntegration:false,automaticDeployments:false,previewWorkflow:'stage-vercel-hub.yml',candidateTarget:'production',candidateSkipDomain:true,promotion:'explicit-certified-deployment',rollback:'explicit-certified-deployment'},production:{canonicalDomain:'thiepn.dev',trafficOwnerUntilCutover:'github-pages',vercelCustomDomainAssignmentAllowed:false}};
const contract={schemaVersion:1,productId:'hub',ci:{requiredSecrets:['VERCEL_TOKEN'],neverProjectEnvironment:['VERCEL_TOKEN']},build:{fixedPublic:{PUBLIC_HUB_ACCOUNT_ENTRY:'https://account.thiepn.dev/hub/entry',PUBLIC_HUB_AUTH_ORIGIN:'https://thiepn.dev'},repositoryVariables:[]},vercel:{productionProvisionedPublic:['PUBLIC_HUB_ACCOUNT_ENTRY','PUBLIC_HUB_AUTH_ORIGIN'],productionForbidden:['THIEPN_HUB_PRIVATE_RUNTIME','PUBLIC_HUB_NOTES_PRIVATE'],neverAllowed:['VERCEL_TOKEN','SUPABASE_SERVICE_ROLE_KEY'],privateRuntime:{activation:'THIEPN_HUB_PRIVATE_RUNTIME',activationValue:'staged-v1',serverOnly:['THIEPN_ACCOUNT_URL'],browserVisible:['PUBLIC_HUB_NOTES_PRIVATE']}}};
afterEach(()=>vi.restoreAllMocks());
describe('P5 product-family Vercel standard',()=>{
 it('keeps the checked-in product, environment and vercel.json contracts valid',async()=>{await expect(validateFiles()).resolves.toMatchObject({product:{projectName:'thiepn-hub'},env:{productId:'hub'}});});
 it('accepts only manual non-Git-linked deployment policy',()=>{expect(validateProduct(structuredClone(product)).projectName).toBe('thiepn-hub');const bad=structuredClone(product);bad.deployment.automaticDeployments=true;expect(()=>validateProduct(bad)).toThrow('Unsafe deployment policy');});
 it('requires Vercel Git deployment to remain disabled',()=>{expect(()=>validateRepoPolicy({git:{deploymentEnabled:true}})).toThrow();expect(()=>validateRepoPolicy({git:{deploymentEnabled:false}})).not.toThrow();});
 it('separates server-only and browser-visible environment names',()=>{expect(validateEnvironmentContract(structuredClone(contract)).productId).toBe('hub');const bad=structuredClone(contract);bad.vercel.privateRuntime.serverOnly=['PUBLIC_SECRET'];expect(()=>validateEnvironmentContract(bad)).toThrow('Server/browser');});
 it('rejects activation and credentials from production project environment',()=>{expect(()=>auditEnvironmentMetadata(contract,{envs:[{key:'THIEPN_HUB_PRIVATE_RUNTIME',target:['production'],type:'plain'},{key:'PUBLIC_HUB_ACCOUNT_ENTRY',target:['production'],type:'plain'},{key:'PUBLIC_HUB_AUTH_ORIGIN',target:['production'],type:'plain'}]})).toThrow('Forbidden production');expect(()=>auditEnvironmentMetadata(contract,{envs:[{key:'VERCEL_TOKEN',target:['production'],type:'sensitive'},{key:'PUBLIC_HUB_ACCOUNT_ENTRY',target:['production'],type:'plain'},{key:'PUBLIC_HUB_AUTH_ORIGIN',target:['production'],type:'plain'}]})).toThrow('Forbidden production');});
 it('ignores preview-only metadata while auditing production',()=>{expect(auditEnvironmentMetadata(contract,{envs:[{key:'THIEPN_HUB_PRIVATE_RUNTIME',target:['preview'],type:'plain'},{key:'PUBLIC_HUB_ACCOUNT_ENTRY',target:['production'],type:'plain'},{key:'PUBLIC_HUB_AUTH_ORIGIN',target:['production'],type:'plain'}]})).toMatchObject({target:'production',count:2});});
 it('never requests decrypted Vercel environment values',async()=>{const fetchImpl=vi.fn(async(url,init)=>{expect(String(url)).toContain('decrypt=false');expect(new Headers(init.headers).get('authorization')).toBe('Bearer token');return Response.json({envs:[]});});await fetchEnvironmentMetadata({token:'token',projectName:'thiepn-hub',fetchImpl});});
 it('requires immutable source SHAs and clean Vercel deployment origins',()=>{expect(validateSourceSha('a'.repeat(40))).toHaveLength(40);expect(()=>validateSourceSha('main')).toThrow();expect(validateDeploymentUrl('https://thiepn-hub-abc.vercel.app/')).toBe('https://thiepn-hub-abc.vercel.app');expect(()=>validateDeploymentUrl('https://evil.test/')).toThrow();});
 it('uses explicit action-specific promotion and rollback confirmations',()=>{expect(validateConfirmation('promote','PROMOTE thiepn-hub')).toBeTruthy();expect(validateConfirmation('rollback','ROLLBACK thiepn-hub')).toBeTruthy();expect(()=>validateConfirmation('promote','yes')).toThrow();});
});
